aws-greengrass/aws-greengrass-shadow-manager

README.md, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/integrationtests/resources/com/aws/greengrass/integrationtests/sync_map.yaml, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/model/Constants.java, src/main/java/com/aws/greengrass/shadowmanager/model/configuration/ShadowSyncConfiguration.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerUnitTest.java
Added a new  `synchronize:shadowDocumentsMap` configuration to support map based shadow documents approach.
Thing Name is used as the key in the map and has been removed from the configuration object fields.
To allow for `synchronize:shadowDocumentsMap` to be merged from any deployment
Added new unit test and integration test.
This change will allow the customers to use the old `list` approach. We will document that the map approach is preferred since a list gets overwritten with each deployment merge. Both the `map` and `list` shadow documents configuration topic will be merged into one list of …
=> feat: add new `synchronize:shadowDocumentsMap` configuration type to accept a map object

src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtils.java, src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtilsConfig.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/ipc/DeleteThingShadowRequestHandler.java, src/main/java/com/aws/greengrass/shadowmanager/ipc/UpdateThingShadowRequestHandler.java, src/main/java/com/aws/greengrass/shadowmanager/model/Constants.java, src/main/java/com/aws/greengrass/shadowmanager/model/ShadowDocument.java, src/main/java/com/aws/greengrass/shadowmanager/model/configuration/ShadowSyncConfiguration.java, src/main/java/com/aws/greengrass/shadowmanager/sync/CloudDataClient.java, src/main/java/com/aws/greengrass/shadowmanager/sync/RequestMerger.java, src/main/java/com/aws/greengrass/shadowmanager/sync/Retryer.java, src/main/java/com/aws/greengrass/shadowmanager/sync/SyncHandler.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/BaseSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategyFactory.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/model/Strategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/model/StrategyType.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerUnitTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/SyncHandlerTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategyTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategyFactoryTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/model/StrategyTest.java
Spilt the real time syncing from the `SyncHandler` into its own class after adding the necessary interfaces and classes to support other sync strategies.
This change will enable shadow manager to support multiple sync strategies.
Added and updated unit tests and integration tests.
**Checklist:**
=> feat: real time syncing into a sync strategy class.

pom.xml
Since upgrading to H2 v2.0 seems to be a breaking change, this will remove the Servlet classes from the shaded jar
https://github.com/aws-greengrass/aws-greengrass-shadow-manager/pull/107
**Checklist:**
=> chore: remove Web Servlet classes from shaded jar.

src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/ipc/UpdateThingShadowRequestHandler.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/CloudDeleteSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/CloudUpdateSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/FullShadowSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/LocalDeleteSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/LocalUpdateSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/SyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategy.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/CloudUpdateSyncRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/LocalUpdateSyncRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategyTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategyTest.java
Do not add the sync request in the queue if the update is not necessary. So we need to check that before we add it to the queue.
Also added some new booleans for tests to ensure that the queue is actually empty. 
We should not have a sync request which does not need to be processed in the queue. This was causing issue in the periodic sync wherein a local update was getting converted to a full sync due to an unnecessary local update request after the last cloud shadow update.
Updated the tests.
**Checklist:**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
=> fix: check if update is necessary before adding sync request.

src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/CloudDeleteSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/CloudUpdateSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/FullShadowSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/SyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategy.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/CloudDeleteSyncRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/FullShadowSyncRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategyTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategyTest.java
If an `AbortedException` is thrown, check the cause to see if it was caused due to an `InterruptedException`. If it is, then rethrow that back to the caller. The `syncLoop` should add this request back in the queue if the sync request failed due to an `InterruptedException`.
There might be times when a sync request fails due to the thread being interrupted (while syncing) or if the thread just dies.
Added / Updated unit tests.
**Checklist:**
=> fix: handle `AbortedException` correctly when syncing with cloud.

pom.xml, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/SyncHandler.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/SyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategy.java, src/test/java/com/aws/greengrass/shadowmanager/sync/SyncHandlerTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategyTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategyTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategyTestBase.java
Cancelling sync threads can cause database exceptions if an I/O operation is occurring when the thread is cancelled.
A semaphore is used along with the existing  flag to force the stopper to wait until the request is finished.
SyncStrategy common logic was refactored into the BaseSyncStrategy class to avoid duplication. 
The `syncLoop` method from the `PeriodicSyncStrategy` class was pulled up to the `BaseSyncStrategy`.  Periodic still uses the non-blocking `poll` and RealTime still uses the blocking `take` to get data off the queue. A permit on the semaphore is acquired before executing the request and there are checks for whether syncing has stopped. A latch is used to wait for threads to exit.
Extra test cases have been added to …
=> fix: wait for executing sync request to finish before cancelling threads

src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/sync/SyncHandler.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategy.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerUnitTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategyTest.java
Only restart syncing on config changes that make a change
Don't block while periodic sync threads are scheduled but not executing
Config can get updated frequently without changing (e.g. timestamp updated) and this causes unnecessary full syncs by restarting
Cancelling periodic sync doesn't need to wait when it's not executing
unit
**Checklist:**
=> fix: improvements to sync stopping behavior

src/main/java/com/aws/greengrass/shadowmanager/PubSubIntegrator.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/ipc/BaseRequestHandler.java, src/main/java/com/aws/greengrass/shadowmanager/ipc/PubSubClientWrapper.java, src/main/java/com/aws/greengrass/shadowmanager/ipc/UpdateThingShadowRequestHandler.java, src/main/java/com/aws/greengrass/shadowmanager/model/Constants.java, src/main/java/com/aws/greengrass/shadowmanager/model/ShadowRequest.java, src/test/java/com/aws/greengrass/shadowmanager/PubSubIntegratorTest.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerUnitTest.java, src/test/java/com/aws/greengrass/shadowmanager/ipc/PubSubClientWrapperTest.java
This will add support for Shadow Manager operations over local PubSub. This change is contingent on the [Nucleus PubSub PR](https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1148).
This would enable customers to perform shadow operations over local PubSub. This would also open doors for Client device integration.
Added new unit tests.
Integration tests will be added once the  [Nucleus PubSub PR](https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1148) is merged in.
**Checklist:**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> feat: add support for shadow operations over local PubSub

README.md, src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtils.java, src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtilsConfig.java, src/integrationtests/java/com/aws/greengrass/integrationtests/RateLimiterTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerDAOImplTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncDirectionalityTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/ShadowIPCTest.java, src/integrationtests/resources/com/aws/greengrass/integrationtests/sync_directionality_bidirectional.yaml, src/integrationtests/resources/com/aws/greengrass/integrationtests/sync_directionality_fromcloudonly.yaml, src/integrationtests/resources/com/aws/greengrass/integrationtests/sync_directionality_fromdeviceonly.yaml, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/model/Constants.java, src/main/java/com/aws/greengrass/shadowmanager/sync/CloudDataClient.java, src/main/java/com/aws/greengrass/shadowmanager/sync/SyncHandler.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/BaseSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/Direction.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/FullShadowSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/OverwriteCloudShadowRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/OverwriteLocalShadowRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerUnitTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/CloudDataClientTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/IotDataPlaneClientFactoryTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/FullShadowSyncRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/OverwriteCloudShadowRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/OverwriteLocalShadowRequestTest.java
Adds the ability to configure Shadow Manager to sync the shadows in a particular direction. With a configuration change, Shadow Manager will either bidirectionality sync shadows or in either one of the directions (i.e. either only from the device to the cloud or from cloud to device).
If the Shadow Manager is configured to be synced from the device to the cloud only, on first launch or after a reconnection, the cloud shadow will be overwritten to have the same content as what the local shadow has.
If the Shadow Manager is configured to be synced from the cloud to the device only, on first launch or after a reconnection, the local shadow will be overwritten to have the same content as what the cloud shadow has.
**Why is this change …
=> feat: add sync directionality

src/main/java/com/aws/greengrass/shadowmanager/PubSubIntegrator.java, src/main/java/com/aws/greengrass/shadowmanager/ipc/PubSubClientWrapper.java, src/test/java/com/aws/greengrass/shadowmanager/PubSubIntegratorTest.java
Ignore response messages for shadow operations over PubSub.
We do not need to process the shadow response messages in Shadow Manager.
Added unit test
**Checklist:**
=> fix: ignore shadow response messages.

src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtils.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/sync/RequestMerger.java, src/main/java/com/aws/greengrass/shadowmanager/sync/SyncHandler.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategy.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerUnitTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/RequestMergerTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/SyncHandlerTest.java
Add ability to set the `syncDirection` in the `RequestMerger` class from the `ShadowManager` configuration subscription.
Also inject the `RequestMerger` class instead of creating a new one every time.
`RequestMerger` needs to know the exact direction in which the sync is configured in order to properly merge in new sync requests based on it.
Added unit tests.
**Checklist:**
=> feat: add sync direction in `RequestMerger` to merge appropriate sync requests

src/main/java/com/aws/greengrass/shadowmanager/util/JsonUtil.java, src/test/java/com/aws/greengrass/shadowmanager/util/JsonUtilTest.java
Updated the code to use the correct depth at the level. Validate the depth of `desired` and `reported` separately.
Allow 6 levels in the `state:desired` and `state:reported` section. IoT shadow allows the shadow state to have 6 levels in it.
Added unit tests
**Checklist:**
=> fix: allow 6 levels in shadow state

src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtils.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/UnhappyUpdateIPCTest.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerUnitTest.java
#129 
Subscribe to the changes on the parent configuration node instead of specific child nodes as the child nodes can be removed during reset. 
If the configuration is updated after reset, the component should behave according to the configuration changes without restarting the component. Without this change, the configuration won't be updated once the reset happens. 
Updated tests. Need to do manual testing. 
**Checklist:**
=> fix: respond to config updates after config reset

src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerTest.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java
When the strategy config is updated from periodic to real time (can also happen during reset), overall sync strategy is not set to real time. This fix properly updates the strategy after comparing with the current strategy. 
Added an integration test that fails without this fix. 
**Checklist:**
=> fix: set correct strategy when the config is updated

src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtils.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncDirectionalityTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java
Fix two tests with possible race conditions. 
- In the tests GIVEN_cloud_sync_not_enabled_WHEN_local_update_THEN_does_not_sync_shadow_to_cloud, we check  if the sync queue is not empty right before checking if it's empty. It is not always guaranteed that both of them will hold true due to timing of the tests. So, remove checking if the queue is not empty completely instead check if the certain number of requests (all) are processed from that queue.
- In the GIVEN_synced_shadow_WHEN_local_update_THEN_cloud_updates, before making an IPC request, this change will make sure that all the requests before that are processed. 
**Any additional information or context required to …
=> test: remove assertNotEmptySyncQueue check

src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerTest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/IotDataPlaneClientWrapper.java, src/test/java/com/aws/greengrass/shadowmanager/sync/IotDataPlaneClientWrapperTest.java
…add tests
Addressing comments from #135 
- Add integ test without mocking cloud to verify that the requests fail when the client does not exist and then retried along with the creation of a new client. 
**Checklist:**
=> test: check that requests are retried when the crypto key service is still loading

src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/configuration/ComponentConfiguration.java, src/main/java/com/aws/greengrass/shadowmanager/configuration/RateLimitsConfiguration.java, src/main/java/com/aws/greengrass/shadowmanager/ipc/InboundRateLimiter.java, src/main/java/com/aws/greengrass/shadowmanager/sync/IotDataPlaneClientWrapper.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerUnitTest.java, src/test/java/com/aws/greengrass/shadowmanager/configuration/RateLimitConfigurationTest.java
Read and trigger configuration updates from the component configuration object whenever it is updated. This PR only moves rate limits configuration. 
**Checklist:**
=> refactor: rate limits configuration updates

pom.xml
Excludes the `uat` folder's contents from getting included into the final uber jar
We are bloating the project with test related code if we don't do it.
=> chore: exclude uat from top level uber jar

uat/testing-features/pom.xml, uat/testing-features/src/main/java/com/aws/greengrass/Assertion.java, uat/testing-features/src/main/java/com/aws/greengrass/AssertionSteps.java
- Add assertion steps to listen to updates from components.
- These steps start up assertion server on the device under test. The components that are running as part of the test can then send assertions to this server which will help us verify the component behavior. 
**Checklist:**
=> test: add assertion server

uat/custom-components/pom.xml, uat/custom-components/src/main/java/com/aws/greengrass/artifacts/ShadowComponent.java, uat/custom-components/src/main/java/com/aws/greengrass/utils/Client.java, uat/custom-components/src/main/resources/recipes/ShadowComponentPing.yaml, uat/custom-components/src/main/resources/recipes/ShadowComponentPong.yaml, uat/testing-features/src/main/java/com/aws/greengrass/AssertionSteps.java, uat/testing-features/src/main/resources/greengrass/features/shadow-1.feature
- Add assertion client in custom components and send assertions in the get shadow operation. 
- Assertions in delete and list will be added in  next PR and shadow-1-3 to shadow-1-13 will be updated accordingly. Assertions for update won't be added. 
**Checklist:**
=> test: add assertion client and validate get shadow assertions in tests 

src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/LocalUpdateSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/util/JsonUtil.java
When cloud updates are received over MQTT, there is a (small) chance that we can receive updates out-of-order.  Also, with the proposal of https://github.com/aws-greengrass/aws-greengrass-shadow-manager/pull/166, cloud updates would be processed asynchronously, further increasing the chances of out-of-order processing.  
Functionally, when we receive out-of-order cloud updates (say, B then A), this is automatically detected and a ConflictError is thrown.  This causes a full sync, which puts the local shadow in sync with the cloud.
The first issue however, is when we receive the other out of order message (A, from the above example) after the conflict has been dealt with.  This update has the incorrect, previous cloud version, and will …
=> fix: handle out-of-order cloud updates

src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtils.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerTest.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/sync/RequestMerger.java, src/main/java/com/aws/greengrass/shadowmanager/sync/SyncHandler.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/DirectionWrapper.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategyFactory.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerUnitTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/RequestMergerTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/SyncHandlerTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategyTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategyTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategyFactoryTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategyTestBase.java
Changes the type of request enqueued when a conflict is detected from a `FullShadowSyncRequest`, to one of `OverwriteCloudShadowRequest`/`OverwriteLocalShadowRequest`/`FullShadowSyncRequest`, based on the sync direction.
Also refactors so that sync direction is wrapped in a class which is injected wherever needed.  This means that all usages will have the same reference to direction, rather than needing to ensure setters are called.
To prevent full syncs from happening when a conflict is detected, when sync direction is not BETWEEN_DEVICE_AND_CLOUD.
new unit tests
**Checklist:**
By submitting this …
=> fix: respect sync direction when queueing full sync on conflict

src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtils.java, src/integrationtests/java/com/aws/greengrass/integrationtests/RateLimiterTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncDirectionalityTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/sync/CloudDataClient.java, src/main/java/com/aws/greengrass/shadowmanager/sync/RequestMerger.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/BaseSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/CloudDeleteSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/CloudUpdateSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/FullShadowSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/LocalDeleteSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/LocalUpdateSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/MergedFullShadowSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/OverwriteCloudShadowRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/OverwriteLocalShadowRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/SyncContext.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/SyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/CloudUpdateSyncRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/FullShadowSyncRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/LocalDeleteSyncRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/LocalUpdateSyncRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/OverwriteCloudShadowRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/OverwriteLocalShadowRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategyTestBase.java
:warning: This change undoes the (unreleased) fix in https://github.com/aws-greengrass/aws-greengrass-shadow-manager/pull/166, which introduces a bug where the IPC thread could potentially be blocked, and takes a different approach by restricting sync info to being read by only one thread.
This change adjusts where `SyncRequest#isUpdateNecessary` is called, so that it is only called when a `SyncRequest` is executing on a sync thread.  This is different than previous behavior, where an IPC or MQTT CRT thread could call this method, to read shadow sync information from the local database to make a decision on whether or not the SyncRequest should be put on the queue.  This ensures that shadow sync information is only read and written to …
=> fix: only read sync from sync thread

uat/testing-features/pom.xml, uat/testing-features/src/main/java/com/aws/greengrass/ShadowSteps.java, uat/testing-features/src/main/resources/greengrass/features/shadow-1.feature, uat/testing-features/src/main/resources/greengrass/features/shadow-2.feature, uat/testing-features/src/main/resources/greengrass/features/shadow-6.feature, uat/testing-features/src/main/resources/greengrass/recipes/recipe.yaml
Modify the uat setup so that the tests run against the current version of the code and not against the artifact already deployed in production.
Required to effectively test uats on our release pipeline
Ran the uats
=> feat: run uats against release candidate

src/main/java/com/aws/greengrass/shadowmanager/ipc/UpdateThingShadowRequestHandler.java, src/test/java/com/aws/greengrass/shadowmanager/ipc/UpdateThingShadowRequestHandlerTest.java, src/test/resources/com/aws/greengrass/shadowmanager/ipc/json_shadow_examples/bad_update_document_with_delta_node.json
Specifying "delta" as part of an update request was allowed, but this does not work when reporting the shadow to IoT Core.
```
InvalidRequestException: State contains an invalid node: 'delta' (Service: IotDataPlane, Status Code: 400
```
**Checklist:**
=> fix: drop reported delta in update shadow

pom.xml, src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtils.java, src/integrationtests/java/com/aws/greengrass/integrationtests/RateLimiterTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerDatabaseTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncDirectionalityTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/integrationtests/resources/com/aws/greengrass/integrationtests/periodic_sync.yaml, src/integrationtests/resources/com/aws/greengrass/integrationtests/sync.yaml, src/main/java/com/aws/greengrass/shadowmanager/ipc/DeleteThingShadowRequestHandler.java, src/main/java/com/aws/greengrass/shadowmanager/sync/SyncHandler.java, uat/testing-features/pom.xml
Fixing the issues in the integration tests that are caused due to timeout and race condition especially in the sync tests for realtime and periodic sync strategies. 
- Countdown latches are added wherever applicable to avoid premature ending of tests.
- Actual testing in some sync test scenarios starts after the initial full shadow sync is performed. This ensures that the assertions (especially for  shadow versions) can be made in a definite way.
**Checklist:**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> test: fix integration tests

uat/custom-components/src/main/java/com/aws/greengrass/artifacts/ShadowReactiveComponent.java, uat/custom-components/src/main/resources/recipes/ShadowComponentPong.yaml, uat/custom-components/src/main/resources/recipes/ShadowReactiveComponentPing.yaml, uat/custom-components/src/main/resources/recipes/ShadowReactiveComponentPong.yaml, uat/testing-features/src/main/resources/greengrass/features/shadow-1.feature
Fix ShadowReactive custom component recipes which is used in 7 UATs of shadow manager.
- Run jar from Run lifecyle but not start up
- Fix number of arguments passed to the run command. 
- Use response objects  as supported by v2 clients instead of `CompletableFuture` objects. 
**Checklist:**
=> fix: shadow1 UATs

src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerDatabaseTest.java, src/integrationtests/resources/com/aws/greengrass/integrationtests/database/corrupted.mv.db, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManagerDatabase.java
When shadow manager DB is corrupted, the component goes into BROKEN state. The database file must be deleted for the component to create a new database and continue working. This change automates this deletion when the migration of DB fails due to corruption.
**Checklist:**
=> fix: remove and recreate DB in the case of corruption

src/integrationtests/java/com/aws/greengrass/integrationtests/SyncDirectionalityTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, uat/testing-features/src/main/resources/greengrass/features/shadow-1.feature
- Refactor bi-directional tests setup to guarantee cloud and and local update requests merge. This is also needed for shadow version assertions.   
- Give enough time for the requests to process before making assertions 
**Checklist:**
=> test: fix sync integ tests and uats

src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerDAOImplTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerDatabaseTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerTest.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManagerDAOImpl.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManagerDatabase.java, src/main/java/com/aws/greengrass/shadowmanager/exception/ShadowManagerDataException.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerDAOImplTest.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerUnitTest.java, uat/testing-features/pom.xml
#186.
Most likely fixes #186 as we are closing the threadpool when the database closes, but the database can technically re-open and in that case the threadpool couldn't be used as it was already shutdown.
Additionally, validates that we are able to get a connection to the database after migration is performed. If we cannot get a connection, then migration is considered a failure and the DB will be deleted and recreated.
Added a scenario to a test which fails without this change when requesting a reinstall for shadow manager.
**Checklist:**
By submitting this pull request, I confirm that you can …
=> fix: validate connection to DB after migration

src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/main/java/com/aws/greengrass/shadowmanager/model/ShadowState.java, src/main/java/com/aws/greengrass/shadowmanager/util/JsonMerger.java, src/main/java/com/aws/greengrass/shadowmanager/util/JsonUtil.java, src/main/resources/json/schema/update_payload_schema.json, src/test/java/com/aws/greengrass/shadowmanager/util/JsonMergerTest.java, src/test/java/com/aws/greengrass/shadowmanager/util/JsonUtilTest.java
Support an empty shadow document,`{"state": {}}`.
According to https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-document.html#device-shadow-empty-fields, `{}` is a valid shadow document.
New unit and integration tests
**Checklist:**
=> fix: support empty state document

src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/main/java/com/aws/greengrass/shadowmanager/model/ShadowState.java, src/main/java/com/aws/greengrass/shadowmanager/util/JsonMerger.java, src/main/java/com/aws/greengrass/shadowmanager/util/JsonUtil.java, src/test/java/com/aws/greengrass/shadowmanager/util/JsonMergerTest.java, src/test/java/com/aws/greengrass/shadowmanager/util/JsonUtilTest.java
Follow-up to https://github.com/aws-greengrass/aws-greengrass-shadow-manager/pull/192. After UATs and more experimentation with IoT test client, I realized `{"state": {}}` will not clear the full shadow; only `{"state": null}` will accomplish this.
Fixed integration tests, more testing with IoT test client.
**Checklist:**
=> fix: clear state only on null

src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/main/java/com/aws/greengrass/shadowmanager/ipc/UpdateThingShadowRequestHandler.java, src/main/java/com/aws/greengrass/shadowmanager/model/ShadowDocument.java
Follow-up to https://github.com/aws-greengrass/aws-greengrass-shadow-manager/pull/193 and https://github.com/aws-greengrass/aws-greengrass-shadow-manager/pull/192.  
When updating a shadow locally with `{"state": null}`, ensure the update response state is `{}`, rather than `null`, because `null` is not a valid shadow state document.
Also refactored logic from `ShadowDocument` constructors into `setFields` methods while I was at it.
**Checklist:**
=> fix: return empty rather than null in update response

src/main/java/com/aws/greengrass/shadowmanager/ipc/DeleteThingShadowRequestHandler.java, src/main/java/com/aws/greengrass/shadowmanager/ipc/GetThingShadowRequestHandler.java, src/main/java/com/aws/greengrass/shadowmanager/ipc/UpdateThingShadowRequestHandler.java
Read the "shadowName" from the shadow request object which defaults the shadow to classic shadow if it isn't provided. This prevents ugly error messages when the customer-provided shadow name is null for any reason.
**Checklist:**
=> fix: default to classic shadow name in requests

src/main/java/com/aws/greengrass/shadowmanager/util/JsonUtil.java, src/test/java/com/aws/greengrass/shadowmanager/util/JsonMergerTest.java
#198 
Previous PRs fixing null handling introduced an issue where shadows which contain the literal key `state` due to a mistakenly recursive call when checking if state is null or empty. This change fixes that problem by removing the recursive call and checking if literally JSON's null value. 
Added a new test case which fails without the change and works properly with the change.
**Checklist:**
=> fix: properly handle when shadow contains a key named state set to null

src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtils.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/FullShadowSyncRequest.java, src/main/java/com/aws/greengrass/shadowmanager/util/JsonMerger.java, src/main/java/com/aws/greengrass/shadowmanager/util/SyncNodeMerger.java, src/test/java/com/aws/greengrass/shadowmanager/sync/model/FullShadowSyncRequestTest.java, src/test/java/com/aws/greengrass/shadowmanager/util/SyncNodeMergerTest.java
- Previously when a full sync was performed, `SyncNodeMerger` would remove any fields that were set to `null` from the shadow document. Then, once this document was merged during the local update, those removed fields were reintroduced since the merge was unaware they had already been set to `null` before. With this fix we now retain null fields inside of `SyncNodeMerger` so that they can be handled and deleted from the local shadow document during the following merges.
- Updated the integration test framework to allow for setting an initial local shadow state before starting the Nucleus. This allows us to simulate receiving cloud updates while the device is not yet running.
Fixes a bug where …
=> fix: retain null fields in sync node merger

.github/workflows/uat.yaml, src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/ShadowIPCTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/UnhappyUpdateIPCTest.java, src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/shadow.yaml, src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/shadowUnhappy.yaml, src/main/java/com/aws/greengrass/shadowmanager/ShadowManagerDAOImpl.java, src/main/java/com/aws/greengrass/shadowmanager/ShadowManagerDatabase.java, src/main/java/com/aws/greengrass/shadowmanager/configuration/ShadowDocSizeConfiguration.java, src/main/java/com/aws/greengrass/shadowmanager/sync/model/BaseSyncRequest.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerDAOImplTest.java
Added a stress test that updates shadow over IPC 1,000 times as fast as possible, causing shadow manager to need to sync to cloud quickly as well. This replicated a customer issue where they saw a nullpointerexception coming from H2. The fix is to simply synchronize all DB access.
I auto-formatted src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/ShadowIPCTest.java, so forgive the large change there. The meaningful change is the addition of test 0 which is the stress test.
**Checklist:**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> fix: just synchronize all DAO operations to avoid H2 threading problems

gdk-config.json, src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java, src/main/java/com/aws/greengrass/shadowmanager/sync/CloudDataClient.java, src/test/java/com/aws/greengrass/shadowmanager/ShadowManagerUnitTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/CloudDataClientTest.java
Run mqtt callbacks in a separate thread to avoid a deadlock situation that happens when the Shadow manager component enters into RUNNING state before the MQTT client connection is successfully created acc to GG. 
Mqtt connect future will be completed with the client only after the first on connect callbacks are triggered. Shadow manager onConnect callback needs the client to be fully formed (connect future to be completed with the mqtt client) for it to use subscribe with it.  Hence, the subscriptions triggered from the callback timeout waiting for the client.
During SM start up, startSyncingShadows is called which calls [updateSubscriptions](https://github.com/aws-greengrass/aws-greengrass-shadow-manager/blob/315d1b9cdf7573f8ad4d99583 …
=> fix: synchronize cloud data client operations properly

.github/workflows/maven.yml, pom.xml, src/integrationtests/java/com/aws/greengrass/integrationtests/NucleusLaunchUtils.java, src/integrationtests/java/com/aws/greengrass/integrationtests/RateLimiterTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/ShadowManagerTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/SyncTest.java, src/main/java/com/aws/greengrass/shadowmanager/sync/RequestQueue.java, src/main/java/com/aws/greengrass/shadowmanager/sync/SyncHandler.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategy.java, src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategyFactory.java, src/test/java/com/aws/greengrass/shadowmanager/sync/RequestQueueTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/SyncHandlerTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategyTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategyTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategyFactoryTest.java, src/test/java/com/aws/greengrass/shadowmanager/sync/strategy/SyncStrategyTestBase.java
Removes the default shadow queue size limit
of 1024 shadows.
Misc changes:
* Updates to upload-artifact v4 as v3 is deprecated
* Updates nucleus dependency version to allow for local builds on M-series macs
By removing bounds on the shadow queue size
users can now have more than 1024 shadows. 'Take'
operation behaviors remain the same however 'Put'
operations will no longer block as waiting for
space is not a thing.
Figuring this out now
The Shadow-Manager has a queue for device shadows. This queue is limited to 1024 shadows by default (but dynamically sized when <1024). This hard limit will prevent customers from having > …
=> Remove bounds on shadow queue size
